[release]
llm_endpoint = "http://localhost:8000/v1/"
llm_model = "Qwen/Qwen3-8B-FP8"
embedding_model = "Qwen/Qwen3-Embedding-4B"
emdedding_endpoint = "http://localhost:8001/v1"
api_key = ""
ndims = 4096
max_tokens = 65536

[default]
api = "/v1"
address = "::"
health = "/health"
system_prompt = "prompts/system.txt"
chat_template = "prompts/template.txt"
max_tokens = 16384
port = 9000
llm_model = "Qwen/Qwen3-VL-4B-Thinking"
llm_endpoint = ""
embedding_model = "Qwen/Qwen3-Embedding-8B"
emdedding_endpoint = ""
api_key = ""
ndims = 4096
identity_server_url = "http://localhost:8000"
[debug]
