repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-merge-conflict
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

-   repo: local
    hooks:
    -   id: cargo-fmt
        name: cargo fmt (local)
        description: cargo fmt
        entry: cargo fmt
        language: system
        types: [rust]     # for rust files only
        args: [--, --check]
        pass_filenames: true
        stages: [pre-commit]

-   repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.15.0
    hooks:
    -   id: pretty-format-yaml
        types: [yaml]
        args: [--indent, '4', --autofix]
        stages: [pre-commit]
