repos:
-   repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.15.0
    hooks:
    -   id: pretty-format-rust
        types: [rust]
        args: [--autofix]
    -   id: pretty-format-yaml
        types: [yaml]
        args: [--indent, '4', --autofix]
# - repo: local
#   hooks:
#   - id: cargo-clippy-fix-unused-imports
#     name: cargo clippy (fix unused imports)
#     types: [rust]
#     entry: >-
#       cargo clippy
#       --fix
#       --allow-staged
#       --allow-dirty
#       --
#       -D unused_imports
#     language: system
#     pass_filenames: false
#     stages: [pre-commit]
