[package]
name = "pvc-ohttp-relay"
version = "0.1.0"
license = "Apache-2.0"
edition.workspace = true

[dependencies]
ohttp-relay = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tokio = { workspace = true }
rustls = { workspace = true }
