[package]
name = "identity"
version = "0.1.0"
license = "Apache-2.0"
edition = { workspace = true }

[dependencies]
anyhow = { workspace = true }
async-trait =  { workspace = true }
rsa = { workspace = true }
blind-rsa = { workspace = true }