apiVersion: v1
kind: Service
metadata:
  name: {{ include "pvc.tee-server.name" . }}
  labels:
    {{- include "pvc.tee-server.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.teeLlm.service.type }}
  ports:
    - port: {{ .Values.teeLlm.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "pvc.tee-server.selectorLabels" . | nindent 4 }}
